### PR TITLE
Add static site generator

### LINKED ISSUE #164: Add static site generator
1. @cthoyt Implement a static site generator, similar to what's available for CONSO ([code](https://github.com/pharmacome/conso), [site](https://pharmacome.github.io/conso/))
2. @bgyori turn on GitHub pages for this repository, serving from main branch `docs/` directory (that's a canned setting)
3. Consider improvements to curation to make site more interesting:
  - More descriptions
  - Reference information for synonyms
  - Classification of entities as complexes, families, or famplexes
  - Lookup of names for xrefs and entities in relations with PyOBO

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #164 

This PR implements a static site generator for famplex. It does not include the actual site, since that will make the diff very big. To generate the static site, install FamPlex in editable mode with `pip install -e .` then run `python -m famplex.html`. This will populate the `/docs` folder with the index (a listing of all entities) and a page for each entity (using a folder structure and an `index.html` inside each`

This PR also improves the `.gitignore` since it does not protect against accidentally committing build artifacts.

Future questions: can the package be further streamlined? The `exports/` and `imports/` code doesn't take advantage of the package structure.

## Home Page

Screen Shot 2021-03-09 at 15 10 57

## Term Page

Screen Shot 2021-03-09 at 15 11 17

### CODE REVIEW

**Comment by bgyori** [comment]
Looks great! Yes, I think when making famplex into a proper package we didn't go further into imports and exports to refactor those to use the package - we could definitely do that if it's useful. Those modules are problematic anyway because they have external dependencies like INDRA that one wouldn't want to install by default. Actually, given that this new html module depends on protmapper, should we add an extra dependency list to the setup?

**Comment by cthoyt** [comment]
I think it would be better to have a few "extras" lists for this kind of stuff. I could also go all out and use PyOBO for looking up names, but that might be a bit tricky if done in a CI scenario because it could use a lot of disk space/memory.

@bgyori what do you think about me leaving some of those fields (specificity, provenance) even if they're blank?

**Comment by johnbachman** [comment]
This looks great! One thing that would be nice to add would be populating the name field for the child entities from their HGNC IDs:
 
Screen Shot 2021-03-09 at 9 52 28 AM

**Comment by cthoyt** [comment]
@johnbachman addressed (for HGNC) in f954b30. We can more generally use the INDRA clients or PyOBO for lookup of other namespaces, if desired. I think we would want to wrap the INDRA clients with the same kind of interface that PyOBO uses, like `indra.clients.get_name(namespace, identifier)` if we wanted to go that route

**Comment by bgyori** [comment]
> Actually, there is a unified interface in INDRA for accessing naming information from the various clients via the OntologyGraph, namely you can do:
> 
> ```
> from indra.ontology.bio import bio_ontology
> bio_ontology.get_name('HGNC', '...')
> ```
> 
> Also, I implemented a web-service back-end for this interface so you can use this code without having to generate and load into memory the ontology graph locally. We just need to configure the URL tot he running INDRA ontology service as an env variable. I think this might be the easiest way to achieve this here without adding large dependencies.

On second thought, instead of using this code, it would make more sense to just use `requests` to talk to the web service... that way INDRA isn't a dependency.

**Comment by cthoyt** [comment]
@bgyori @johnbachman now the code can work 2 different ways depending on if `indra` is installed and the bio_ontology can be used directly. You can run `tox -e html` to make the export from inside the famplex directory directly. If we want, we could add INDRA to the dependencies to sped this up greatly, since there's a speed limit on  hitting the API (unless I make it much more complicated with threads)

**Comment by cthoyt** [comment]
@bgyori I think this is ready now that the bioontology lookup is fixed. Should we actually generate the docs in this PR, or should we do a separate PR that sets up a github action to do it?

**Comment by bgyori** [comment]
Great, I think we can start a new PR for the Github actions deployment.

**Review by bgyori — APPROVED** [review]

**Pull request merged**
