### PR TITLE
Pico hgnc updates

### PR DESCRIPTION
**Pull request by AlexanderPico**
Updated a handful of outdated "previous symbols" using the HGNC website as reference.

### CODE REVIEW

**Comment by AlexanderPico** [comment]
Hmm. I intended two PR two branches, but it looks like my TLE and ICAM family additions made it into this same branch somehow.

Will this work for you?

**Comment by bgyori** [comment]
Yes, I can sort it out from here, thanks for the contribution!

**Comment by bgyori** [comment]
@AlexanderPico thanks again for the contribution. Unfortunately I'm not able to push to this PR to complete the changes that are needed - usually there is a checkbox that is checked by default when you open a PR, allowing maintainers to push to the PR branch. If you look at this page now, do you still see that perhaps? If not, I will open a new PR with the changes.

**Comment by AlexanderPico** [comment]
Sorry for the hassle. Looks like this is a commonly requested feature for `organization-owned` forks like this case, https://github.com/orgs/community/discussions/5634. 

I will add you as a collaborator to our org as a possible workaround.

Also feel free to make a PR to our fork, which I will then merge, which I think is how @cthoyt got around this same issues.

**Comment by bgyori** [comment]
Thanks @AlexanderPico, after you gave access to the repo, things worked. To recap the changes:
- Updating HGNC resource version required a corresponding change in INDRA to make the validation script not error.
- New FamPlex terms are also listed in the entities.csv file
- I added a couple of synonyms in the grounding_map.csv. This is not strictly necessary but useful. I found TLE to be ambiguous and most often used to represent something other than the protein family so I didn't include "TLE" as a synonym.
- I update all the exports

**Pull request merged**
