### PR TITLE
Import definitions via xrefs

### PR DESCRIPTION
**Pull request by cthoyt**
This PR adds a script that pulls in definitions using new (unreleased) pyobo code from (https://github.com/pyobo/pyobo/pull/98 -  once I fix the mocks in the testing I will merge it). It prioritizes getting the definitions for famplex entries based on their xrefs in the following order:

- interpro
- mesh

### CODE REVIEW

**Comment by bgyori** [comment]
Great! Just note the issue https://github.com/sorgerlab/famplex/issues/159 with non-exact InterPro mappings.

**Comment by cthoyt** [comment]
@bgyori I just reorganized to have a priority list and make this a bit more flexible

**Comment by cthoyt** [comment]
@bgyori this isn't a perfect PR and won't be so easy to re-run until I re-release PyOBO with some fixes (unless you want to install pyobo in the development mdoe), but it gets the job done of adding 424 descriptions (~60% of famplexes). I made a priority list (which you can feel free to change) where interpro is at the bottom - only one entry gets assigned a name that way.

**Comment by bgyori** [comment]
I think this is really great, the descriptions all look appropriate!

**Review by bgyori — APPROVED** [review]

**Comment by cthoyt** [comment]
Closes #168

**Pull request merged**
