### PR TITLE
Add BEL namespace exporter

### LINKED ISSUE #37: Add BEL namespace exporter

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #37

### CODE REVIEW

**Comment by bgyori** [comment]
Great, thanks! I wonder if we should also check in the famplex.belns file itself so that it can be accessed via a URL in the repo?

**Comment by cthoyt** [comment]
There are two commits - one adds the exporter and [one adds the BELNS file](https://github.com/sorgerlab/famplex/pull/38/commits/e7765df02de2906440917a699b2d13275cad681a). I would vote for adding the BELNS file as well!

**Comment by bgyori** [comment]
Sorry, I totally missed it, it's added! I'll move it to the export folder if you don't mind, we have some other export formats in there

**Comment by cthoyt** [comment]
Oh, I missed the export folder. Also, we need to make sure that each version is assigned its own file name (so there's the one url-one resource integrity)

**Comment by bgyori** [comment]
That could be tricky, what about linking to a version of the file through a specific commit? Like for as a similar example, this URL points to the version of the file in a specific version: https://raw.githubusercontent.com/sorgerlab/famplex/0c77ee175e65f6e63c73045bb20ff9176c185fb6/export/famplex.obo

**Comment by cthoyt** [comment]
That's a great solution! Might we add an example on the readme to explain this potential users?

**Comment by bgyori** [comment]
Let's merge this first and I'll write a blurb about exports more generally in another PR!

**Pull request merged**
